version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: epicfood
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: epic_food
      MYSQL_USER: epicfood
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"
